services:
  - type: web
    name: telegram-ai-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_ai_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    plan: free
    pythonVersion: "3.11" 