services:
  - type: web
    name: telegram-ai-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: WEBHOOK_URL
        value: https://telegram-ai-bot-xopipop.onrender.com/webhook
      - key: PORT
        value: 8080
    autoDeploy: true
    plan: free
